"""Pack the HD art into js/world/atlas_hd.js (data URIs, so the game runs from file:// and as a single file, and the
share card's canvas never gets tainted).

    python3 assets/hd/pack.py            # after running the area generators (assets/hd/<area>/build.py)

Reads assets/hd/out/<area>/manifest.json for every area that has one and embeds every PNG it references
(manifest entries name their image in "file"; nested manifests are walked). Writes:
    LS.ATLAS_HD = { <area>: { manifest: {...}, img: { <file>: 'data:image/png;base64,...' } } }
"""
import base64, json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'assets', 'hd', 'out')
DEST = os.path.join(ROOT, 'js', 'world', 'atlas_hd.js')
AREAS = [a for a in (sys.argv[1:] or ['chars', 'terrain', 'rail', 'town', 'props', 'interiors'])]


def files_in(node, acc):
    if isinstance(node, dict):
        for k, v in node.items():
            if isinstance(v, str) and v.endswith(('.png', '.webp')): acc.add(v)   # file, lit, parts...
            else: files_in(v, acc)
    elif isinstance(node, list):
        for v in node: files_in(v, acc)
    return acc


def previous():
    # the last packed atlas, so an area whose generator is mid-rebuild keeps its last good art
    try:
        t = open(DEST).read(); return json.loads(t[t.index('LS.ATLAS_HD = ') + 14:].rstrip().rstrip(';'))
    except Exception:
        return {}


def main():
    atlas, total, prev = {}, 0, previous()
    for area in AREAS:
        mf = os.path.join(OUT, area, 'manifest.json')
        if not os.path.exists(mf): continue
        man = json.load(open(mf)); img = {}
        for f in sorted(files_in(man, set())):
            p = os.path.join(OUT, area, f)
            if not os.path.exists(p): continue
            data = open(p, 'rb').read(); total += len(data)
            mime = 'image/webp' if f.endswith('.webp') else 'image/png'
            img[f] = f'data:{mime};base64,' + base64.b64encode(data).decode()
        wanted = files_in(man, set())
        if len(img) < len(wanted) and area in prev:
            print(f'  ! {area}: {len(wanted) - len(img)} images missing (mid-rebuild?), keeping the previous {area} art', file=sys.stderr)
            atlas[area] = prev[area]; continue
        atlas[area] = {'manifest': man, 'img': img}
        print(f'{area}: {len(img)} images')
    with open(DEST, 'w') as o:
        o.write('/* LINESIDE HD art atlas: generated by assets/hd/pack.py from assets/hd/out/. Do not edit. */\n')
        o.write('window.LS = window.LS || {};\nLS.ATLAS_HD = ')
        json.dump(atlas, o, separators=(',', ':'))
        o.write(';\n')
    print(f'{os.path.relpath(DEST, ROOT)}: {total / 1e6:.2f} MB of images, {os.path.getsize(DEST) / 1e6:.2f} MB file')


if __name__ == '__main__':
    main()
